In [1]:
import numpy as np          # type: ignore

<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
dimension of array
</div>

> ### **one dim** >>

In [2]:
a = [2,3,6,5,4,7,8] 
b = np.array(a) 

print(a)
print(type(a),"\n")

print(b)
print(type(b))

[2, 3, 6, 5, 4, 7, 8]
<class 'list'> 

[2 3 6 5 4 7 8]
<class 'numpy.ndarray'>


> ### **two dim** >>

In [3]:
a = [[1,2,3],[5,3,6],[9,6,5]] 
b = np.array(a) 

print(a)
print(type(a),"\n")

print(b)
print(type(b))

[[1, 2, 3], [5, 3, 6], [9, 6, 5]]
<class 'list'> 

[[1 2 3]
 [5 3 6]
 [9 6 5]]
<class 'numpy.ndarray'>


> ### **three dim** >>

In [4]:
a = [[[1,2,3],[5,3,6],[9,6,5]]] 
b = np.array(a) 

print(a)
print(type(a),"\n")

print(b)
print(type(b))

[[[1, 2, 3], [5, 3, 6], [9, 6, 5]]]
<class 'list'> 

[[[1 2 3]
  [5 3 6]
  [9 6 5]]]
<class 'numpy.ndarray'>


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
ndim
</div>

In [5]:
a = np.array(10)
print(f"a is {a.ndim} dimension")

b = np.array([10 , 20]) 
print(f"b is {b.ndim} dimension")

c = np.array([ [1, 2] , [3, 4] ] )
print(f"c is {c.ndim} dimension")

d = np.array([ [[5, 6],[7, 9]] , [[1, 3],[4, 8]] ] )
print(f"d is {d.ndim} dimension")

a is 0 dimension
b is 1 dimension
c is 2 dimension
d is 3 dimension


In [6]:
my_custom_array = np.array([1, 2, 3], ndmin=3) 

print(my_custom_array)
print(my_custom_array.ndim)
print(my_custom_array[0, 0, 0])

[[[1 2 3]]]
3
1


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
dtype
</div>

In [7]:
my_array4   = np.array([1, 2, 3], dtype=float) 
my_array4_1 = np.array([1, 2, 3], dtype="f") 

my_array5   = np.array([1.5, 20.15, 3.601], dtype=int) 
my_array5_1 = np.array([1.5, 20.15, 3.601], dtype="i") 

# my_array6   = np.array(["Osama_Elzero", "B", "Ahmed"], dtype=int)

print(my_array4.dtype) 
print(my_array4_1.dtype)

print(my_array5.dtype) 
print(my_array5_1.dtype)

# print(my_array6.dtype) # Value Error

float64
float32
int32
int32


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
astype
</div>

#### 👉 To change datatype

In [8]:
my_array7 = np.array([0, 1, 2, 3, 0, 4]) 

print(my_array7.dtype) 
print('------')
my_array7 = my_array7.astype('float') 
print(my_array7.dtype)
print('------')
my_array7 = my_array7.astype('bool') 
print(my_array7.dtype) 

int32
------
float64
------
bool


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
compare [shape - size - dtype - ndim -len]
</div>

In [9]:
first__list = [1, 2, 3, 4]         
second_list = [5, 6, 7, 8]
two_d_array = np.array([first__list,second_list])

print(two_d_array)
print('-------')
print(two_d_array.shape)   ## return row and column
print(two_d_array.size)    ## return size
print(two_d_array.dtype)   ## return datatype
print('-------')
print(two_d_array.ndim)
print(len(two_d_array))    

[[1 2 3 4]
 [5 6 7 8]]
-------
(2, 4)
8
int32
-------
2
2


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
ones - zeros
</div>

In [10]:
print(np.ones([2,4]))           # = print(np.ones(shape=[2,4]))
print("----------------------")
print(np.zeros([2,4]))          # = print(np.zeros(shape=[2,3]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
eye - identity
</div>

In [11]:
print ( np.eye( N = 3,            ## N => Number of rows
                M = 5,            ## M => Number of columns
                k = 2))           ## k => Index of the diagonal (main diagonal (0) is default)
print("----------------------")
print(np.identity(n = 5))       ## identity(n=Size of the array)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
----------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
diag
</div>

In [12]:
a = np.diag(np.array([5,12,4,-1,3])) 
b = np.diag(np.array([5,12,4,-1,3]),k=3) 

print(a) 
print("-------")
print(b) 

[[ 5  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  3]]
-------
[[ 0  0  0  5  0  0  0  0]
 [ 0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
full
</div>

In [13]:
a = np.full(4,25) 
b = np.full((2,3),25) 

print(a) 
print("-------")
print(b) 

[25 25 25 25]
-------
[[25 25 25]
 [25 25 25]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
empty
</div>

In [14]:
a = np.empty((3,2)) 
print(a) 

[[0. 1.]
 [2. 3.]
 [0. 4.]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
Array Indexing & Slicing
</div>

In [15]:
one_d_array = np.array([1,2,3,4,5,6])
two_d_array = np.array([one_d_array, one_d_array + 6, one_d_array + 12])

print(f"(1)\n{one_d_array}")
print("----------------------")
print(f"(2)\n{two_d_array}")
print("----------------------")
print(f"(3)\n{two_d_array[2]}")           # Get the item at index 2
print("----------------------")
print(f"(4)\n{two_d_array[1:]}")          # Get a slice from index 3 to the end
print("----------------------")
print(f"(5)\n{two_d_array[1,4]}")
print("----------------------")
print(f"(6)\n{two_d_array[1:, 4:]}")
print("----------------------")
print(f"(7)\n{two_d_array[0:2,2:4]}")
print("----------------------")
print(f"(8)\n{two_d_array[::-1]}")        # Slice backwards to reverse the array
print("----------------------")
print(f"(9)\n{two_d_array[::-1,::-1]}")   # Reverse both dimensions

(1)
[1 2 3 4 5 6]
----------------------
(2)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
----------------------
(3)
[13 14 15 16 17 18]
----------------------
(4)
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
----------------------
(5)
11
----------------------
(6)
[[11 12]
 [17 18]]
----------------------
(7)
[[ 3  4]
 [ 9 10]]
----------------------
(8)
[[13 14 15 16 17 18]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]
----------------------
(9)
[[18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]
