In [1]:
import numpy as np          # type: ignore

<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
arange
</div>

#### 👉 arange(start,end,steps)

In [2]:
print(np.arange(10))
print("-----------------")
print(np.arange(10,100,5))
print("----------------")
print(np.arange(100,10,-5))

[0 1 2 3 4 5 6 7 8 9]
-----------------
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
----------------
[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
reshape
</div>

In [3]:
a =np.arange(18).reshape(3,6) 
print(a) 
print('-------')

b =np.arange(18).reshape(2,3,3) 
print(b) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
-------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
linspace
</div>

In [4]:
print(np.linspace(1,100,10))  

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
sort & argsort
</div>

#### 👉 ```np.sort```: Returns the sorted array.
#### 👉 ```np.argsort```: Returns the indices that can be used to sort the array

In [5]:
first = np.array([3,5,7,2,9,4,1])
sorted_first = np.sort(first)
second = np.array([[3,5,7,2],[9,4,1,6]])

print(sorted_first)
print("=================================")
print(second)
print("=================================")
print(np.sort(second,axis=0))
print("-------")
print(np.sort(second,axis=1))
print("-------")
print(np.sort(second,axis=None)) # stretch array

[1 2 3 4 5 7 9]
[[3 5 7 2]
 [9 4 1 6]]
[[3 4 1 2]
 [9 5 7 6]]
-------
[[2 3 5 7]
 [1 4 6 9]]
-------
[1 2 3 4 5 6 7 9]


In [6]:
arr = np.array([3, 1, 2])
sorted_arr = np.sort(arr)

print(sorted_arr)                   # Output: [1 2 3]
############
indices = np.argsort(arr)
print(indices)                      # Output: [1 2 0]
############
sorted_arr_using_indices = arr[np.argsort(arr)]
print(sorted_arr_using_indices)     # Output: [1 2 3]

[1 2 3]
[1 2 0]
[1 2 3]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
ravel & flatten
</div>

In [7]:
one_d_array = np.array([1,2,3,4,5,6])
two_d_array = np.array([one_d_array, one_d_array + 6, one_d_array + 12])

print(two_d_array)
print("----------------------")
print(two_d_array.reshape(-1))
print("----------------------")
print(np.ravel(a=two_d_array,order='C'))  # C (by rows)
print("----------------------")
print(np.ravel(a=two_d_array,order='F'))  # F (by columns)
print("----------------------")

# flatten
print(two_d_array.flatten("C"))  # row [left to right]
print("----------------------")
print(two_d_array.flatten("F"))  # col [up to down] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
----------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
----------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
----------------------
[ 1  7 13  2  8 14  3  9 15  4 10 16  5 11 17  6 12 18]
----------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
----------------------
[ 1  7 13  2  8 14  3  9 15  4 10 16  5 11 17  6 12 18]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
rot90
</div>

#### 👉 k=Number of 90 degree rotations [Counterclockwise <^]

In [8]:
print(np.rot90(two_d_array,k=1))  
print("----------------------")
print(np.rot90(two_d_array,k=2))

[[ 6 12 18]
 [ 5 11 17]
 [ 4 10 16]
 [ 3  9 15]
 [ 2  8 14]
 [ 1  7 13]]
----------------------
[[18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
roll
</div>

In [9]:
print(two_d_array,"\n========")
print(np.roll(a= two_d_array, shift = 2,axis=1))    # shift elements 2 positions In each row

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] 
[[ 5  6  1  2  3  4]
 [11 12  7  8  9 10]
 [17 18 13 14 15 16]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
flip , Transpose
</div>

#### 👉 flip[lr/ud]

In [10]:
print(two_d_array)
print("----------------------")
print(np.fliplr(two_d_array))       # flip left-right    reverse 
print("----------------------")
print(np.flipud(two_d_array))       # flip up-down       reverse
print("----------------------")
print(two_d_array.T)                # Transpose

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
----------------------
[[ 6  5  4  3  2  1]
 [12 11 10  9  8  7]
 [18 17 16 15 14 13]]
----------------------
[[13 14 15 16 17 18]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]
----------------------
[[ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
concatenate , hstack , vstack
</div>

#### 👉 concatenate((arr1,arr2), axis= __ )

In [11]:
a = np.array([ [4, 8], [6, 1] ])
b = np.array([ [3, 5], [7, 2] ])

print(a) 
print("-----")
print(b)
print("--------------------")
print(np.concatenate((a,b), axis=0))      ## axis=0   (row)
print("--------------------")
print(np.vstack((a,b)))

[[4 8]
 [6 1]]
-----
[[3 5]
 [7 2]]
--------------------
[[4 8]
 [6 1]
 [3 5]
 [7 2]]
--------------------
[[4 8]
 [6 1]
 [3 5]
 [7 2]]


In [12]:
print(np.concatenate((a,b), axis=1))      ## axis=1   (col)
print("--------------------")
print(np.hstack((a,b)))
print("-----")

x=np.concatenate((a,b), axis=None)        ## = ravel by row
print(x)
print("------------------")
print(np.ravel(a=x,order='C'))

[[4 8 3 5]
 [6 1 7 2]]
--------------------
[[4 8 3 5]
 [6 1 7 2]]
-----
[4 8 6 1 3 5 7 2]
------------------
[4 8 6 1 3 5 7 2]


In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arrx = np.stack((arr1, arr2), axis=1)
arry = np.stack((arr1, arr2), axis=0)

print(arrx)
print("-----")
print(arry)

[[1 4]
 [2 5]
 [3 6]]
-----
[[1 2 3]
 [4 5 6]]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
split
</div>

In [14]:
x = [11,22,33,44,55,66,77,88]
#    0  1  2  3  4  5  6  7

x1, x2, x3 = np.split(x, (3,6))
print(x1,x2,x3)

x1, x2, x3 = np.split(x, (1,5)) 
print(x1, x2, x3)

x1, x2, x3 = np.split(x, (0,3)) 
print(x1, x2, x3)

x1, x2, x3 = np.split(x, (6,3)) 
print(x1, x2, x3)

x1, x2, x3 = np.split(x, (4,0)) 
print(x1, x2, x3)

[11 22 33] [44 55 66] [77 88]
[11] [22 33 44 55] [66 77 88]
[] [11 22 33] [44 55 66 77 88]
[11 22 33 44 55 66] [] [44 55 66 77 88]
[11 22 33 44] [] [11 22 33 44 55 66 77 88]


In [15]:
x=np.concatenate((a,b), axis=None)        ## = ravel by row
print(x)
print("-----")
print(x.reshape(2,4))
print("-----")
print(np.split(x,2))   # it run with array not with list
print("-----")
print(np.split(x,4))

[4 8 6 1 3 5 7 2]
-----
[[4 8 6 1]
 [3 5 7 2]]
-----
[array([4, 8, 6, 1]), array([3, 5, 7, 2])]
-----
[array([4, 8]), array([6, 1]), array([3, 5]), array([7, 2])]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
unique
</div>

In [16]:
y = [2,2,2,2,1,2,1,1,2,2]
print(np.unique(y))

[1 2]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
where
</div>

In [17]:
x=np.arange(10)
print(x)
print(np.where(x==3))       # return indices
print("--------------")

y=np.array([[1,2,3,4],[5,3,6,8]])
print(y)
print(np.where(y==3))   

# (array([0, 1], dtype=int64), array([2, 1], dtype=int64))
#         row                        column    =>so (0,2),(1,1) == 3

[0 1 2 3 4 5 6 7 8 9]
(array([3], dtype=int64),)
--------------
[[1 2 3 4]
 [5 3 6 8]]
(array([0, 1], dtype=int64), array([2, 1], dtype=int64))


In [18]:
print(np.where(x<3))
print("----")
print(np.where(x<3,0,1))   # 0 => true condition , 1 => false condition

(array([0, 1, 2], dtype=int64),)
----
[0 0 0 1 1 1 1 1 1 1]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
diff
</div>

#### 👉 The difference between point and prev

In [19]:
print(np.diff([2,3,8,9,5,1]))   
print(np.diff([1,1,1,1,1,1]))   

[ 1  5  1 -4 -4]
[0 0 0 0 0]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
compress
</div>

#### 👉 compress( condition or show_number_by_T_or_F, array )

In [20]:
y = np.arange(1,20)

print(y)
print(np.compress(y%5==0,y))                              # compress( condition            , array )
print(np.compress([True,False,True,False,True,False],y))  # compress( show_number_by_T_or_F, array )

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5 10 15]
[1 3 5]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
clip
</div>

#### 👉 clip(array,min,max) : num< min = min & num> max = max 

In [21]:
z = [12,23,20,25,9,2,22,13,5,18] 
print(z)
print(np.clip(z,7,11)) 

[12, 23, 20, 25, 9, 2, 22, 13, 5, 18]
[11 11 11 11  9  7 11 11  7 11]


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
repeat , tile
</div>

In [22]:
x=np.repeat([0,1,2],3)
y=np.tile([0,1,2],3)

print(x)
print("--------------")
print(y) 
print("--------------")
print(x.shape)
print(y.shape)

[0 0 0 1 1 1 2 2 2]
--------------
[0 1 2 0 1 2 0 1 2]
--------------
(9,)
(9,)


In [23]:
arr1=np.repeat([[3,2]],5,axis=0) 
arr2=np.repeat([[3,2]],5,axis=1) 

print(arr1)
print("--------------")
print(arr2)
print("--------------")
print(arr1.shape)
print(arr2.shape)

[[3 2]
 [3 2]
 [3 2]
 [3 2]
 [3 2]]
--------------
[[3 3 3 3 3 2 2 2 2 2]]
--------------
(5, 2)
(1, 10)


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
ndenumerate , nditer
</div>

#### 👉 ```ndenumerate``` is used to iterate over an array and return the index of the element
#### 👉 ```nditer``` is used to iterate over an array

In [24]:
one_d_array = np.array([1,2,3,4,5,6])
two_d_array = np.array([one_d_array, one_d_array + 6, one_d_array + 12])

print(two_d_array)
print('--------')
for index,i in np.ndenumerate(two_d_array):
    print(index, i)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
--------
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(0, 5) 6
(1, 0) 7
(1, 1) 8
(1, 2) 9
(1, 3) 10
(1, 4) 11
(1, 5) 12
(2, 0) 13
(2, 1) 14
(2, 2) 15
(2, 3) 16
(2, 4) 17
(2, 5) 18


In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):        
    print(x)

1
3
5
7


<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
copy , view
</div>

#### 👉 ```copy``` : no edit in original
#### 👉 ```view``` : edit in original

In [26]:
arr1= np.array([1,2,3,4,5])
arr2=np.copy(arr1)      # = arr1.copy()
print("arr1>> ", arr1)

arr1[0]=6
print("arr1>> ", arr1)
print("arr2>> ", arr2)
print("======================")

arr1= np.array([1,2,3,4,5])
arr2=arr1.view()
print("arr1>> ", arr1)

arr1[0]=6
print("arr1>> ", arr1)
print("arr2>> ", arr2)

arr1>>  [1 2 3 4 5]
arr1>>  [6 2 3 4 5]
arr2>>  [1 2 3 4 5]
arr1>>  [1 2 3 4 5]
arr1>>  [6 2 3 4 5]
arr2>>  [6 2 3 4 5]
