> # 100 numpy exercises
> * This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. 
> * The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.
> * If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>.

<div style="width: 100%; height: 10px; background: linear-gradient(to right, orange, red, orange, red, orange); border-radius: 5px; margin: 20px 0;"></div>

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

#### 👉 2. Print the numpy version and the configuration (★☆☆)
`hint: np.__version__, np.show_config)`

In [2]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/abdal/anaconda3/Library/include
    lib directory: C:/Users/abdal/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

#### 3. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 👉 4. How to find the memory size of any array (★☆☆)
`hint: size, itemsize`

In [4]:
Z = np.zeros((10,10))
print(f"{Z.size * Z.itemsize} bytes")

800 bytes


#### 👉 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`hint: np.info`

In [5]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`hint: array[::-1]`

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [9]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.0802363  0.33255639 0.1362457 ]
  [0.52828145 0.15827175 0.35546329]
  [0.84420616 0.46578091 0.83674221]]

 [[0.60975407 0.85915455 0.89017969]
  [0.57323866 0.54880951 0.15125165]
  [0.58672544 0.50812229 0.50507663]]

 [[0.83162364 0.88695292 0.95644198]
  [0.11808433 0.80160969 0.90642416]
  [0.02735813 0.92146385 0.10201239]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0009027528407237195 0.985782887616894


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5171112701056905


#### 👉 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`hint: array[1:-1, 1:-1]`

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 👉 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`hint: np.pad`

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
0 * np.nan              
np.nan == np.nan              
np.inf > np.nan              
np.nan - np.nan              
np.nan in set([np.nan])              
0.3 == 3 * 0.1              

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 👉 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [19]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 👉 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
`hint: array[::2]`

In [20]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 👉 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`hint: np.unravel_index`

In [21]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 👉 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`hint: np.tile`

In [22]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [23]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.12160774 -0.59073652 -1.45471083  0.88171307 -1.03001452]
 [ 0.04591047 -0.72232298 -0.80700311 -0.66857588  0.34657261]
 [-1.25526889  1.71406455  0.49570723  0.24169807  0.0580714 ]
 [ 0.52871509  0.24464908  1.85979164 -0.91332317  0.47871266]
 [-1.59580401 -1.28268858  1.59891943  1.52687207  0.42065887]]


#### 👉 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
`hint: np.dtype`

In [24]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 👉 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`hint: >, <`

In [27]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 👉 26. What is the output of the following script? (★☆☆)
print(sum(range(5),-1))             
from numpy import *             
print(sum(range(5),-1))             

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 👉 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z               
2 << Z >> 2               
Z <- Z               
1j*Z               
Z/1/1               
Z<Z>Z               

#### 28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)            
np.array(0) // np.array(0)            
np.array([np.nan]).astype(int).astype(float)            

In [29]:
print(np.array(0) / np.array(0),"\n")
print(np.array(0) // np.array(0),"\n")
print(np.array([np.nan]).astype(int).astype(float),"\n")

nan 

0 

[-2.14748365e+09] 



C:\Users\abdal\AppData\Local\Temp\ipykernel_3252\1235801228.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0),"\n")
C:\Users\abdal\AppData\Local\Temp\ipykernel_3252\1235801228.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0),"\n")
C:\Users\abdal\AppData\Local\Temp\ipykernel_3252\1235801228.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float),"\n")


#### 👉 29. How to round away from zero a float array ? (★☆☆)
`hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [30]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z),"\n")

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[  4.  -1.  -1.  -5. -10.  -2. -10.   1.   6.  -2.] 

[  4.  -1.  -1.  -5. -10.  -2. -10.   1.   6.  -2.]


#### 👉 30. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [31]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`hint: np.seterr, np.errstate`

In [32]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 👉 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)          

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\abdal\AppData\Local\Temp\ipykernel_3252\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 👉 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`hint: np.datetime64, np.timedelta64`

In [34]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2025-02-14
2025-02-15
2025-02-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
`hint: np.arange(dtype=datetime64['D'])`

In [35]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

In [36]:
A = np.ones(3)*1
B = np.ones(3)*2
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 👉 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`hint: %, np.floor, astype, np.trunc`

In [37]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[4. 1. 9. 3. 4. 4. 5. 4. 7. 8.]
[4. 1. 9. 3. 4. 4. 5. 4. 7. 8.]
[4. 1. 9. 3. 4. 4. 5. 4. 7. 8.]
[4 1 9 3 4 4 5 4 7 8]
[4. 1. 9. 3. 4. 4. 5. 4. 7. 8.]


#### 👉 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
`hint: np.arange`

In [38]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [39]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 👉 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
`hint: np.fromiter`

In [40]:
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`hint: np.linspace`

In [41]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [42]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00514396 0.21045322 0.22489619 0.26055548 0.56690122 0.5991799
 0.59931596 0.64050479 0.76948099 0.81731406]


#### 41. How to sum a small array faster than np.sum? (★★☆)
`hint: np.add.reduce`

In [43]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 👉 42. Consider two random array A and B, check if they are equal (★★☆)
`hint: np.allclose, np.array_equal`

In [44]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 👉 43. Make an array immutable (read-only) (★★☆)
`hint: flags.writeable`

In [45]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1        # assignment destination is read-only

#### 👉 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`hint: np.sqrt, np.arctan2`

In [46]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R,"\n")
print(T)

[0.93113294 0.68833406 0.02144277 1.0234644  0.62343075 0.48463367
 0.36331872 1.04873552 0.66704167 1.03798081] 

[0.94032605 0.33854713 0.09158219 0.68683187 0.61208573 0.5163171
 0.77702206 0.37304335 1.32821244 0.84999165]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [47]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.04990059 0.         0.04815838 0.10386408 0.08885131 0.35247469
 0.58507773 0.63107047 0.52397529 0.0210738 ]


#### 👉 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`hint: np.meshgrid`

In [48]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 👉 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`hint: np.subtract.outer`

In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 👉 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`hint: np.iinfo, np.finfo, eps`

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    print("--------------------")
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    print("*********")

-128
127
--------------------
-2147483648
2147483647
--------------------
-9223372036854775808
9223372036854775807
--------------------
-3.4028235e+38
3.4028235e+38
1.1920929e-07
*********
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
*********


#### 👉 49. How to print all the values of an array? (★★☆)
`hint: np.set_printoptions`

In [51]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 👉 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`hint: argmin`

In [52]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

80


#### 👉 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`hint: dtype`

In [53]:
Z = np.zeros(10, [ ('position',[('x', float, 1),
                                ('y', float, 1)]),
                    ('color',  [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\abdal\AppData\Local\Temp\ipykernel_3252\3294291644.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position',[('x', float, 1),


#### 👉 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`hint: np.atleast_2d, T, np.sqrt`

In [54]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         1.1495035  0.85623173 0.23244602 0.35339344 0.27898698
  0.73706333 0.97568369 0.64878972 0.17597418]
 [1.1495035  0.         0.82433911 1.0403424  0.98426598 1.07517522
  0.9194684  0.2143226  0.5890971  1.08207554]
 [0.85623173 0.82433911 0.         0.62966945 0.50912142 0.60669159
  1.21150042 0.62041351 0.38347523 0.92868221]
 [0.23244602 1.0403424  0.62966945 0.         0.12171779 0.06737452
  0.84449384 0.8450719  0.48068862 0.35499272]
 [0.35339344 0.98426598 0.50912142 0.12171779 0.         0.10561952
  0.90594565 0.7800496  0.40319634 0.46153787]
 [0.27898698 1.07517522 0.60669159 0.06737452 0.10561952 0.
  0.91177262 0.87480592 0.50193858 0.41630772]
 [0.73706333 0.9194684  1.21150042 0.84449384 0.90594565 0.91177262
  0.         0.87863618 0.8343936  0.56482313]
 [0.97568369 0.2143226  0.62041351 0.8450719  0.7800496  0.87480592
  0.87863618 0.         0.37949731 0.93073983]
 [0.64878972 0.5890971  0.38347523 0.48068862 0.40319634 0.50193858
  0.8343936  0.37949

In [55]:
# Much faster with scipy
import scipy                # type: ignore
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial        # type: ignore

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.35196907 0.38785321 0.25731705 0.41684924 0.51463192
  0.16866527 0.25724824 0.73722331 0.26552667]
 [0.35196907 0.         0.5353791  0.60482688 0.28846723 0.20102296
  0.5143638  0.22806202 0.42566886 0.49509037]
 [0.38785321 0.5353791  0.         0.39939801 0.33815487 0.56832075
  0.46467021 0.5937056  0.71993149 0.1427379 ]
 [0.25731705 0.60482688 0.39939801 0.         0.5970934  0.74861941
  0.14807107 0.50108569 0.96037906 0.26234289]
 [0.41684924 0.28846723 0.33815487 0.5970934  0.         0.23802432
  0.57502391 0.46391397 0.38697219 0.37779502]
 [0.51463192 0.20102296 0.56832075 0.74861941 0.23802432 0.
  0.68311376 0.42900828 0.22782772 0.57824902]
 [0.16866527 0.5143638  0.46467021 0.14807107 0.57502391 0.68311376
  0.         0.37262198 0.90584527 0.32262056]
 [0.25724824 0.22806202 0.5937056  0.50108569 0.46391397 0.42900828
  0.37262198 0.         0.65164448 0.50004186]
 [0.73722331 0.42566886 0.71993149 0.96037906 0.38697219 0.22782772
  0.90584527 0.65164

#### 👉 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
 `hint: view and [:] =`

In [56]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[53 49 34 69 30 24 44 36 86 58]


#### 👉 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`hint: np.genfromtxt`


In [57]:
from io import StringIO
# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                ,  , 9,10,11 ''')
Z = np.genfromtxt(s, delimiter=",", dtype="int")
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 👉 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`hint: np.ndenumerate, np.ndindex`

In [58]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 👉 56. Generate a generic 2D Gaussian-like array (★★☆)
`hint: np.meshgrid, np.exp`

In [59]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 👉 57. How to randomly place p elements in a 2D array? (★★☆)
`hint: np.put, np.random.choice`

In [60]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


#### 👉 58. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [61]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.31688254  0.06255908 -0.13072079  0.31605142 -0.19903365  0.43938121
   0.43970085 -0.32502481 -0.22835316 -0.05767762]
 [ 0.02459377  0.54954119  0.12234855 -0.07418887 -0.36272575  0.2915319
  -0.34699035  0.20429784 -0.24070326 -0.16770502]
 [ 0.26944608  0.23705988 -0.31508387  0.3196819   0.27661422 -0.46753681
  -0.0223336   0.00426455  0.28786556 -0.58997793]
 [ 0.32352012  0.16136975  0.17127577 -0.12433258 -0.29043199  0.13020495
  -0.29655237  0.24753936  0.03128516 -0.35387818]
 [ 0.28392049 -0.2544212  -0.38485312 -0.23040668 -0.33076906 -0.11768325
   0.24340201  0.24853794  0.48159942  0.06067344]]


#### 👉 59. How to sort an array by the nth column? (★★☆)
`hint: argsort`

In [62]:
Z = np.random.randint(0,10,(3,3))
print(Z,"\n")
print(Z[Z[:,1].argsort()])

[[9 1 3]
 [8 2 0]
 [6 7 7]] 

[[9 1 3]
 [8 2 0]
 [6 7 7]]


#### 👉 60. How to tell if a given 2D array has null columns? (★★☆)
`hint: any, ~`

In [63]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [64]:
# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

[False False  True]


#### 👉 61. Find the nearest value from a given value in an array (★★☆)
`hint: np.abs, argmin, flat`

In [65]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4585650331624387


#### 👉 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`hint: np.nditer`

In [66]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 👉 63. Create an array class that has a name attribute (★★☆)
`hint: class method`

In [67]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 👉 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`hint: np.bincount | np.add.at`

In [68]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 4. 1. 3. 5. 4. 3. 3. 2. 1.]


In [69]:
# Another solution
np.add.at(Z, I, 1)
print(Z)

[7. 7. 1. 5. 9. 7. 5. 5. 3. 1.]


#### 👉 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`hint: np.bincount`

In [70]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 👉 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`hint: np.unique`

In [71]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [72]:
# Faster version
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64


#### 👉 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`hint: sum(axis=(-2,-1))`

In [73]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[61 47 47 60]
 [56 53 44 51]
 [43 59 69 48]]


In [74]:
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[61 47 47 60]
 [56 53 44 51]
 [43 59 69 48]]


#### 👉 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`hint: np.bincount`

In [75]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.49123905 0.50632818 0.59931793 0.48625344 0.39778152 0.5619844
 0.54637798 0.47713273 0.31153444 0.41267454]


In [76]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.491239
1    0.506328
2    0.599318
3    0.486253
4    0.397782
5    0.561984
6    0.546378
7    0.477133
8    0.311534
9    0.412675
dtype: float64


#### 👉 69. How to get the diagonal of a dot product? (★★★)
`hint: np.diag`

In [77]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

array([0.63055344, 1.38136503, 1.47430084, 0.79863331, 1.54593584])

In [78]:
# Fast version
np.sum(A * B.T, axis=1)

array([0.63055344, 1.38136503, 1.47430084, 0.79863331, 1.54593584])

In [79]:
# Faster version
np.einsum("ij,ji->i", A, B)

array([0.63055344, 1.38136503, 1.47430084, 0.79863331, 1.54593584])

#### 👉 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`hint: array[::4]`

In [80]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 👉 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)
`hint: array[:, :, None]`

In [81]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 👉 72. How to swap two rows of an array? (★★★)
`hint: array[[]] = array[[]]`

In [82]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 👉 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`hint: repeat, np.roll, np.sort, view, np.unique`

In [83]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(12, 40) (12, 73) (13, 23) (13, 49) (13, 74) (13, 99) (23, 99) (27, 31)
 (27, 38) (30, 76) (30, 91) (31, 38) (35, 58) (35, 78) (40, 73) (41, 56)
 (41, 96) (45, 47) (45, 84) (46, 55) (46, 74) (46, 83) (47, 84) (49, 74)
 (55, 55) (56, 96) (58, 78) (74, 83) (76, 91)]


#### 👉 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`hint: np.repeat`

In [84]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 👉 75. How to compute averages using a sliding window over an array? (★★★)
`hint: np.cumsum, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)`

In [85]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [86]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 👉 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`hint: from numpy.lib import stride_tricks, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)`

In [87]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [88]:
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 👉 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`hint: np.logical_not, np.negative`

In [89]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [90]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.91289289,  0.21103641, -0.30636498, -0.17720702, -0.29672324,
        0.82675181,  0.67250645,  0.12245203, -0.80077898, -0.46289441,
        0.38013093, -0.84616638,  0.59835887, -0.78031885,  0.71103469,
       -0.02706591, -0.10047902, -0.69750609,  0.18429556, -0.13711715,
        0.53680457, -0.31241758, -0.41470624,  0.07501159, -0.9206707 ,
        0.55022158, -0.28924672,  0.73153921,  0.46938901,  0.02835045,
       -0.94834731, -0.73458729, -0.65513066, -0.83665997,  0.2783387 ,
        0.04904888, -0.88135843,  0.2520123 , -0.68891487, -0.31851749,
       -0.16935431, -0.69393158, -0.9753999 , -0.25387623,  0.95159012,
        0.94691438,  0.61759782, -0.43212898, -0.80959148, -0.37789651,
        0.26179617,  0.92468653,  0.13309693, -0.3994503 , -0.0736972 ,
        0.70564248, -0.99038504, -0.6859995 ,  0.38938214,  0.89096258,
        0.64137635, -0.75400547, -0.42887294, -0.6056037 , -0.04893992,
        0.45968914,  0.14093996, -0.05862387,  0.62599754, -0.40

#### 👉 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
`No hints provided...`

In [91]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.06987684  3.68863327  0.30967304 13.98144308 15.95618133  8.11046587
  9.7690178   0.67594734  3.52692902  5.77520016]


#### 👉 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
`No hints provided...`

In [92]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.716037    9.97686481  7.99183009  0.27770245  5.98622878  1.8858935
   1.4933998  10.01172571 10.5630887   3.96879025]
 [ 2.09469339  4.17936516  1.88863748  6.80726743  1.44626486  4.3621703
   3.0593611   2.63201837  5.81422133  3.79617595]
 [ 4.90972399  6.36367733  3.8557019   5.88429067  1.66330165  2.50952536
   6.79884463  2.85411277  8.57271291  7.56585443]
 [ 4.32568583  8.861835    7.2828205   1.35699424  8.77579966  1.38533015
   4.25917066 12.16962035  8.29444925  1.24446397]
 [ 2.13882158  3.25707114  2.0006555   2.24504395  7.20107736  3.72263591
  10.79580143  9.79239884  1.90113139  8.29999504]
 [ 7.1688091  10.30153709  8.27357736  0.35902712  5.85744821  2.14522756
   2.18772339  9.96290012 11.00411141  4.64761418]
 [ 3.95197725  6.49582698  4.32390882  3.99389569  1.49321807  1.8707088
   2.47708197  5.55501333  7.72140999  3.90229945]
 [ 6.24858468  7.96079524  5.51667823  4.03943255  0.19947035  0.81898777
   6.63255257  4.73044986  9.94030029  7.84025122]
 [ 

#### 👉 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`hint: minimum maximum`

In [93]:
Z = np.random.randint(0,10,(10,10))
shape    = (5,5)
fill     = 0
position = (1,1)

R  = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop  = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop  = (np.minimum(Z_stop,Zs)).tolist()

r    = tuple(slice(start,stop) for start,stop in zip(R_start,R_stop))
z    = tuple(slice(start,stop) for start,stop in zip(Z_start,Z_stop))
R[r] = Z[z]
print(Z)
print(R)

[[6 3 1 3 3 5 5 6 7 7]
 [7 0 1 0 2 8 0 9 5 6]
 [1 7 3 0 6 6 0 5 5 1]
 [1 7 8 8 3 4 1 3 3 5]
 [3 5 4 7 5 4 5 7 9 8]
 [7 8 8 9 3 9 9 2 7 9]
 [6 6 7 6 3 9 2 7 8 0]
 [2 1 6 8 3 4 6 8 3 9]
 [1 4 2 2 0 7 5 1 1 8]
 [7 3 6 1 5 1 3 2 6 1]]
[[0 0 0 0 0]
 [0 6 3 1 3]
 [0 7 0 1 0]
 [0 1 7 3 0]
 [0 1 7 8 8]]


#### 👉 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`hint: stride_tricks.as_strided, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)`

In [94]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [95]:
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 👉 82. Compute a matrix rank (★★★)
`hint: np.linalg.svd, np.linalg.matrix_rank`

In [96]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)  # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [97]:
rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 👉 83. How to find the most frequent value in an array?
`hint: np.bincount, argmax`

In [98]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


#### 👉 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`hint: stride_tricks.as_strided, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)`

In [99]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 4 4]
   [1 0 1]
   [1 1 2]]

  [[4 4 0]
   [0 1 2]
   [1 2 3]]

  [[4 0 0]
   [1 2 4]
   [2 3 4]]

  [[0 0 4]
   [2 4 2]
   [3 4 1]]

  [[0 4 1]
   [4 2 3]
   [4 1 0]]

  [[4 1 2]
   [2 3 1]
   [1 0 0]]

  [[1 2 4]
   [3 1 0]
   [0 0 0]]

  [[2 4 3]
   [1 0 2]
   [0 0 0]]]


 [[[1 0 1]
   [1 1 2]
   [2 4 3]]

  [[0 1 2]
   [1 2 3]
   [4 3 2]]

  [[1 2 4]
   [2 3 4]
   [3 2 2]]

  [[2 4 2]
   [3 4 1]
   [2 2 4]]

  [[4 2 3]
   [4 1 0]
   [2 4 3]]

  [[2 3 1]
   [1 0 0]
   [4 3 1]]

  [[3 1 0]
   [0 0 0]
   [3 1 4]]

  [[1 0 2]
   [0 0 0]
   [1 4 3]]]


 [[[1 1 2]
   [2 4 3]
   [1 3 1]]

  [[1 2 3]
   [4 3 2]
   [3 1 3]]

  [[2 3 4]
   [3 2 2]
   [1 3 4]]

  [[3 4 1]
   [2 2 4]
   [3 4 4]]

  [[4 1 0]
   [2 4 3]
   [4 4 3]]

  [[1 0 0]
   [4 3 1]
   [4 3 3]]

  [[0 0 0]
   [3 1 4]
   [3 3 4]]

  [[0 0 0]
   [1 4 3]
   [3 4 4]]]


 [[[2 4 3]
   [1 3 1]
   [4 1 4]]

  [[4 3 2]
   [3 1 3]
   [1 4 1]]

  [[3 2 2]
   [1 3 4]
   [4 1 1]]

  [[2 2 4]
   [3 4 4]
   [1 1 2]]

  [[2 4 3]
   

In [100]:
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[2 2 4]
   [3 0 2]
   [1 1 4]]

  [[2 4 0]
   [0 2 2]
   [1 4 0]]

  [[4 0 2]
   [2 2 1]
   [4 0 4]]

  [[0 2 1]
   [2 1 3]
   [0 4 2]]

  [[2 1 4]
   [1 3 3]
   [4 2 1]]

  [[1 4 0]
   [3 3 3]
   [2 1 1]]

  [[4 0 0]
   [3 3 2]
   [1 1 3]]

  [[0 0 0]
   [3 2 0]
   [1 3 1]]]


 [[[3 0 2]
   [1 1 4]
   [2 2 0]]

  [[0 2 2]
   [1 4 0]
   [2 0 0]]

  [[2 2 1]
   [4 0 4]
   [0 0 3]]

  [[2 1 3]
   [0 4 2]
   [0 3 2]]

  [[1 3 3]
   [4 2 1]
   [3 2 2]]

  [[3 3 3]
   [2 1 1]
   [2 2 1]]

  [[3 3 2]
   [1 1 3]
   [2 1 1]]

  [[3 2 0]
   [1 3 1]
   [1 1 1]]]


 [[[1 1 4]
   [2 2 0]
   [1 4 4]]

  [[1 4 0]
   [2 0 0]
   [4 4 0]]

  [[4 0 4]
   [0 0 3]
   [4 0 0]]

  [[0 4 2]
   [0 3 2]
   [0 0 3]]

  [[4 2 1]
   [3 2 2]
   [0 3 3]]

  [[2 1 1]
   [2 2 1]
   [3 3 3]]

  [[1 1 3]
   [2 1 1]
   [3 3 1]]

  [[1 3 1]
   [1 1 1]
   [3 1 0]]]


 [[[2 2 0]
   [1 4 4]
   [0 1 4]]

  [[2 0 0]
   [4 4 0]
   [1 4 1]]

  [[0 0 3]
   [4 0 0]
   [4 1 4]]

  [[0 3 2]
   [0 0 3]
   [1 4 2]]

  [[3 2 2]
   

#### 👉 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
`hint: class method`

In [101]:
class Symmetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symmetric, self).__setitem__((i,j), value)
        super(Symmetric, self).__setitem__((j,i), value)

def symmetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symmetric)

S      = symmetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42

print(S)

[[ 1  9 16 12 16]
 [ 9  0  0 10  9]
 [16  0  2 42  6]
 [12 10 42  3  9]
 [16  9  6  9  3]]


#### 👉 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`hint: np.tensordot`

In [102]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 👉 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`hint: np.add.reduceat, from numpy.lib.stride_tricks import sliding_window_view (np>=1.20.0)`

In [103]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z,  np.arange(0, Z.shape[0], k), axis=0),
                                        np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [104]:
# alternative solution:
Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 👉 88. How to implement the Game of Life using numpy arrays? (★★★)
`No hints provided...`

In [105]:
def iterate(Z):
    # Count neighbors
    N =(Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
        Z[1:-1,0:-2]                + Z[1:-1,2:] +
        Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0

#### 👉 89. How to get the n largest values of an array (★★★)
`hint: np.argsort | np.argpartition`

In [106]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [107]:
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9999 9996 9998 9997]


#### 👉 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`hint: np.indices`

In [108]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 👉 91. How to create a record array from a regular array? (★★★)
`hint: np.core.records.fromarrays`

In [109]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 👉 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
`hint: np.power, *, np.einsum`

In [110]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.05 s ± 212 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
567 ms ± 53.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
370 ms ± 56.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 👉 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`hint: np.where`

In [111]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 5 7]


#### 👉 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
`No hints provided...`

In [112]:
Z = np.random.randint(0,5,(10,3))
print(Z)
print("--------------")
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
print("--------------")
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 3 2]
 [3 3 3]
 [2 0 1]
 [4 2 4]
 [4 3 0]
 [1 2 1]
 [1 4 0]
 [1 3 3]
 [0 1 0]
 [4 2 2]]
--------------
[[4 3 2]
 [2 0 1]
 [4 2 4]
 [4 3 0]
 [1 2 1]
 [1 4 0]
 [1 3 3]
 [0 1 0]
 [4 2 2]]
--------------
[[4 3 2]
 [2 0 1]
 [4 2 4]
 [4 3 0]
 [1 2 1]
 [1 4 0]
 [1 3 3]
 [0 1 0]
 [4 2 2]]


#### 👉 95. Convert a vector of ints into a matrix binary representation (★★★)
`hint: np.unpackbits`

In [113]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1],"\n")

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]] 

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 👉 96. Given a two dimensional array, how to extract unique rows? (★★★)
`hint: np.ascontiguousarray | np.unique`

In [114]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ,"\n")

# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]] 

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


#### 👉 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`hint: np.einsum`

In [115]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)             # np.sum(A)
np.einsum('i,i->i', A, B)       # A * B
np.einsum('i,i', A, B)          # np.inner(A, B)
np.einsum('i,j->ij', A, B)      # np.outer(A, B)

array([[3.57190458e-02, 4.78986821e-02, 4.90466161e-02, 8.28675154e-02,
        2.91632344e-03, 8.55850709e-02, 2.02795828e-02, 7.78040280e-02,
        2.93313383e-02, 7.78322508e-02],
       [1.27027397e-01, 1.70341754e-01, 1.74424144e-01, 2.94701176e-01,
        1.03713010e-02, 3.04365600e-01, 7.21201409e-02, 2.76693930e-01,
        1.04310837e-01, 2.76794299e-01],
       [5.55921584e-02, 7.45482155e-02, 7.63348291e-02, 1.28972764e-01,
        4.53888706e-03, 1.33202294e-01, 3.15625951e-02, 1.21092088e-01,
        4.56505029e-02, 1.21136014e-01],
       [5.61260092e-02, 7.52641010e-02, 7.70678714e-02, 1.30211287e-01,
        4.58247393e-03, 1.34481433e-01, 3.18656902e-02, 1.22254934e-01,
        4.60888840e-02, 1.22299281e-01],
       [8.29610465e-02, 1.11249467e-01, 1.13915658e-01, 1.92468070e-01,
        6.77345207e-03, 1.98779864e-01, 4.71013537e-02, 1.80707615e-01,
        6.81249586e-02, 1.80773166e-01],
       [3.32759676e-01, 4.46225524e-01, 4.56919711e-01, 7.71996199e-01,
   

#### 👉 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`hint: np.cumsum, np.interp`

In [116]:
phi = np.arange(0, 10*np.pi, 0.1)
a   = 1
x   = a*phi*np.cos(phi)
y   = a*phi*np.sin(phi)

dr    = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r     = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 👉 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`hint: np.logical_and.reduce, np.mod`

In [117]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 👉 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`hint: np.percentile`

In [118]:
X = np.random.randn(100)        # random 1D array
N = 1000                        # number of bootstrap samples
idx     = np.random.randint(0, X.size, (N, X.size))
means   = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.26828305  0.14894977]
