In [1]:
import numpy as np          # type: ignore

<div style="background-color:rgb(85, 78, 79) ; color: #ffffff; width: 100%; height: 50px; text-align: center; font-weight: bold; line-height: 50px; margin: 10px 0; font-size: 24px;">
[add/ subtract/ multiply/ divide]reduce - outer - accumlate
</div>

In [2]:
a = np.arange(15) 
b = np.add.reduce(a)     # add.add(array)
b1= np.add.outer(a,10)   # add.outer(array, array or num)
b2= np.add.accumulate(a) # add.accumulate(array)

print(a)
print(b)
print(b1)
print(b2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
105
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105]


In [3]:
c = np.multiply.reduce(a)     
c1= np.multiply.outer(a,10)  
c2= np.multiply.accumulate(a) 
print(a)
print(c)
print(c1)
print(c2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
0
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [4]:
d = np.subtract.reduce(a)     
d1= np.subtract.outer(a,10)  
d2= np.subtract.accumulate(a) 
print(a)
print(d)
print(d1)
print(d2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-105
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4]
[   0   -1   -3   -6  -10  -15  -21  -28  -36  -45  -55  -66  -78  -91
 -105]


In [5]:
e = np.divide.reduce(a)     
e1= np.divide.outer(a,10)  
e2= np.divide.accumulate(a) 
print(a)
print(e)
print(e1)
print(e2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
0.0
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 👉 **`power.reduce(array)`**

In [6]:
f = np.power.reduce(np.arange(2,5))
print(f)

4096
